# Air configuration for hot reload in development
# https://github.com/cosmtrek/air

root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  # Just plain old shell command. You could use `make` as well.
  cmd = "go build -o ./tmp/main cmd/api/main.go"
  # Binary file yields from `cmd`.
  bin = "tmp/main"
  # Customize binary.
  full_bin = "./tmp/main"
  # Watch these filename extensions.
  include_ext = ["go", "tpl", "tmpl", "html", "yaml", "yml"]
  # Ignore these filename extensions or directories.
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "docs", ".git", "node_modules"]
  # Watch these directories if you specified.
  include_dir = []
  # Exclude files.
  exclude_file = []
  # Exclude specific regular expressions.
  exclude_regex = ["_test\\.go"]
  # Exclude unchanged files.
  exclude_unchanged = true
  # Follow symlink for directories
  follow_symlink = true
  # This log file places in your tmp_dir.
  log = "air.log"
  # Poll files for changes instead of using fsnotify.
  poll = false
  # Poll interval (defaults to 10ms)
  poll_interval = 1000 # ms
  # It's not necessary to trigger build each time file changes if it's too frequent.
  delay = 1000 # ms
  # Stop running old binary when build errors occur.
  stop_on_root = false
  # Send interrupt signal before killing process (windows does not support this feature)
  send_interrupt = false
  # Delay after sending interrupt signal
  kill_delay = "0s"

[log]
  # Show log time
  time = false
  # Only show main log (silences watcher, build, runner logs)
  main_only = false

[color]
  # Customize each part's color. If no color found, use the raw application log.
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  # Delete tmp directory on exit
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true